pipeline {
    environment {
        registry = "singla/merchant"
        registryCredential = 'dockerhub'
    }
    agent any
    stages {
        stage('Build') {
            steps {
                sh script: '''
                    echo "I am in build step"
                    chmod +x gradlew
                    ./gradlew build
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                script {
                          dockerImage = docker.build registry + ":$BUILD_NUMBER"
                        }
            }
        }
        stage('Publish DockerImage')
        {
            steps {
            script{
               docker.withRegistry( '', registryCredential ) {
                            dockerImage.push()
                            }
                  }


            }
        }
    }
    post{
        always{
            deleteDir()
        }
    }
}
