pipeline {
    environment {
        registry = "singla/merchant"
        registryCredential = 'dockerhub'
    }
    agent any
    stages {
        stage('Build') {
            steps {
                sh script: '''
                    echo "I am in build step"
                    chmod +x gradlew
                    ./gradlew build
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Building DockerImage ="
                    docker build -t "merchant" .
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')F
        {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerHub', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
                          sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
                          sh 'docker push shanem/spring-petclinic:latest'

            }
        }
    }
    }
    post{
        always{
            deleteDir()
        }
    }
}

